version: '3'

services:
    python:
        container_name: 'data-python'
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - ./backend:/app
